# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_fasthtml',
                'doc_host': 'https://inayet.github.io',
                'git_url': 'https://github.com/inayet/nbdev_fasthtml',
                'lib_path': 'nbdev_fasthtml'},
  'syms': { 'nbdev_fasthtml.core': {'nbdev_fasthtml.core.foo': ('core.html#foo', 'nbdev_fasthtml/core.py')},
            'nbdev_fasthtml.fasthtml_practice': {}}}
